# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

#1

In [35]:
import numpy as np
arr = np.random.uniform(0,20,(4,7))
arr/(arr.max()-arr.min())-arr.min()/(arr.max()-arr.min())

array([[0.60149786, 0.06477218, 0.90231779, 0.93361906, 0.66514876,
        0.23167547, 0.13783069],
       [0.06878   , 0.65464862, 0.47664521, 0.60473136, 0.35587024,
        0.75464045, 0.76851077],
       [1.        , 0.06925902, 0.92038771, 0.5812554 , 0.76060448,
        0.5286759 , 0.        ],
       [0.91825743, 0.68106073, 0.05641077, 0.59921898, 0.61651037,
        0.73994115, 0.47677183]])

#2

In [13]:
matr = np.matrix(np.random.randint(0,10,(8,10)))

In [14]:
matr

matrix([[7, 5, 1, 4, 3, 4, 6, 4, 2, 5],
        [8, 7, 9, 9, 1, 7, 4, 6, 5, 7],
        [3, 0, 0, 4, 9, 9, 3, 4, 9, 2],
        [2, 3, 5, 7, 6, 7, 0, 3, 7, 9],
        [5, 4, 8, 1, 2, 8, 3, 6, 2, 1],
        [4, 0, 2, 4, 5, 0, 0, 9, 2, 9],
        [5, 2, 8, 7, 8, 1, 4, 7, 3, 8],
        [8, 4, 2, 9, 2, 5, 9, 7, 7, 3]])

In [17]:
print(matr.min)

<bound method matrix.min of matrix([[7, 5, 1, 4, 3, 4, 6, 4, 2, 5],
        [8, 7, 9, 9, 1, 7, 4, 6, 5, 7],
        [3, 0, 0, 4, 9, 9, 3, 4, 9, 2],
        [2, 3, 5, 7, 6, 7, 0, 3, 7, 9],
        [5, 4, 8, 1, 2, 8, 3, 6, 2, 1],
        [4, 0, 2, 4, 5, 0, 0, 9, 2, 9],
        [5, 2, 8, 7, 8, 1, 4, 7, 3, 8],
        [8, 4, 2, 9, 2, 5, 9, 7, 7, 3]])>


#3


In [40]:
a = np.array([1, 2, 3])
b =  np.array([2, 4, 5])

In [41]:
x = np.linalg.norm(a-b)
x

3.0

№4

In [124]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
X = (np.linalg.inv(A)@-C)@np.linalg.inv(B)
X

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

Лабораторная работа


In [62]:
import numpy as np
my_data = np.loadtxt('minutes_n_ingredients.csv',dtype = int,skiprows = 1,delimiter = ',')
#1
my_data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [27]:
my_data_transp = my_data.T.copy()

In [28]:
#2
np.median(my_data_transp[1:],axis = 1)

array([40.,  9.])

In [29]:
np.average(my_data_transp[1:],axis = 1)

array([2.16010017e+04, 9.05528000e+00])

In [30]:
np.min(my_data_transp[1:],axis = 1)

array([0, 1])

In [31]:
np.max(my_data_transp[1:],axis = 1)

array([2147483647,         39])

In [32]:
#3
np.quantile(my_data_transp[1:],0.75,axis = 1)

array([65., 11.])

In [33]:
time = my_data_transp[1]

In [34]:
quantile = np.quantile(time,0.75)
quantile

65.0

In [35]:
time = time[np.where(time < quantile)]
time.shape


(73106,)

In [36]:
#4
len(time[time == 0 ])

479

In [37]:
my_data_transp[1] = np.where(my_data_transp[1]==0,1,my_data_transp[1])


In [68]:
len(my_data[my_data[:,1] == 0])
my_data[my_data[:,1] == 0] = 1

In [69]:
len(my_data[my_data[:,1] == 0])

0

In [145]:
np.where(my_data_transp[1]==0)

(array([], dtype=int64),)

In [162]:
my_data_transp.shape

(3, 100000)

In [70]:
#5
unique = np.unique(my_data[:,1:],axis=0)
unique.shape

(4176, 2)

In [71]:
#6
np.unique(my_data[:,2:],axis=0,return_counts = True)

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [37],
        [39]]),
 array([  492,   924,  2884,  5479,  7874,  9328, 10579, 10887, 10542,
         9548,  8262,  6574,  4985,  3639,  2583,  1760,  1237,   787,
          566,   376,   214,   161,   105,    68,    50,    28,    16,
           16,    12,    12,     3,     1,     2,     1,     3,     1,
            1], dtype=int64))

In [117]:
#7
unique_5 = unique[unique[:,1] <= 5]

In [118]:
unique_5.shape

(745, 2)

In [75]:
#8
ingredient_per_minute = unique[:,1] / unique[:,0]
max(ingredient_per_minute)

23.0

In [95]:
#9
np.mean(unique[:,1][np.argsort(unique[:,0])][::-1][:100])


6.63

In [116]:
#10
unique[np.random.choice(unique.shape[0], 10, replace=False), :]

array([[ 450,   13],
       [ 405,   20],
       [ 120,   12],
       [  82,    4],
       [ 189,    9],
       [  55,   22],
       [ 128,    6],
       [  64,    8],
       [ 180,   17],
       [1445,    4]])

In [107]:
#11
np.sum(unique[:,1] < np.mean(unique[:,1]) )/len(unique)*100

57.543103448275865

In [112]:
#12
simple =((unique[:,0] <= 20) & (unique[:,1] <=5))
recipe = np.column_stack([unique, np.transpose(simple)])
recipe

array([[         1,          1,          1],
       [         1,          2,          1],
       [         1,          3,          1],
       ...,
       [    259205,          2,          0],
       [    259260,          7,          0],
       [2147483647,          8,          0]])

In [115]:
#13
round(np.sum(recipe[:,2] == 1 )/len(recipe)*100)

2.0

In [123]:
#14
short = recipe[recipe[:,1] < 10]
mid = recipe[(recipe[:,1] >= 10) & (recipe[:,1] <= 20)]
long = recipe[recipe[:,1] > 20]
recipe_3d = np.array([short[:min(len(short),len(mid),len(long))],mid[:min(len(short),len(mid),len(long))],long[:min(len(short),len(mid),len(long))]])
recipe_3d.shape


(3, 326, 3)

In [120]:
recipe_3d

array([[[    1,     1,     1],
        [    1,     2,     1],
        [    1,     3,     1],
        ...,
        [   41,     6,     0],
        [   41,     7,     0],
        [   41,     8,     0]],

       [[    1,    10,     0],
        [    1,    11,     0],
        [    1,    12,     0],
        ...,
        [   39,    14,     0],
        [   39,    15,     0],
        [   39,    16,     0]],

       [[    1,    23,     0],
        [    2,    21,     0],
        [    2,    25,     0],
        ...,
        [ 3000,    27,     0],
        [ 4440,    28,     0],
        [43380,    22,     0]]])